In [1]:
import numpy as np

In [2]:
# simulate relevant cli arguments from ciwgan

class Namespace:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

args = Namespace(train_batch_size = 5, num_categ = 3)

### Approach 1
This approach doesn't distingish between the order of the words (e.g. "greasy water" vs "water greasy"), but the lower dimensionality may help with training

In [3]:
def random_c():
    c = np.zeros((args.train_batch_size, args.num_categ))
    for _ in range(2):
        idxs = np.random.randint(args.num_categ, size=args.train_batch_size)
        c[np.arange(args.train_batch_size), idxs] = 1

    return c

In [4]:
print(random_c())

[[1. 1. 0.]
 [0. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]


### Approach 2
This approaches encodes the order by doubling the code length, n.b. in the arguments, num_categ should be set to double the number of unique words

In [65]:
args.num_categ = 6

def random_c():
    assert args.num_categ % 2 == 0, "num_categ should be double the number of unique words"
    
    c = np.zeros((args.train_batch_size, args.num_categ))
    idxs = np.random.randint(args.num_categ//2, size=(2, args.train_batch_size))
    #adjust indicies to create the second code
    idxs[1,:] += args.num_categ//2

    #when the same code is in both the first and second slot, change to a one-hot vector
    for i in range(args.train_batch_size):
        if(idxs[0,i]+args.num_categ//2 == idxs[1,i]):

            #randomize whether the 1 goes in the first or second slot
            if (np.random.randint(2) == 0):
                idxs[0,i] = idxs[1,i]
            else:
                idxs[1,i] = idxs[0,i]
                
    c[np.arange(args.train_batch_size), idxs] = 1
    return c

In [80]:
print(random_c())

[[0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]
